const $=id=>document.getElementById(id),ctx=$('imageCanvas').getContext('2d');
let state,token,video,frame=0,annotation,boxes=[],boxHistory=[],selectedBox=null,dirty=false,tabName='annotation',image=new Image(),drag=null,ghost=null;
let detections=[],selections=[],rows=[],previewModel=null,jobId=null,pollTimer=null,suggestions=[],loadingFrame=false;
let traceResults=[],traceVideoId=null,traceFetchVersion=0,tracePreviewVersion=0,traceLoading=false,traceBusy=false;
function message(text,title='准备就绪'){$('status').textContent=text;$('jobTitle').textContent=title}
async function api(path,body,raw=false){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'X-Session-Token':token,'Content-Type':raw?'application/octet-stream':'application/json'},body:raw?body:JSON.stringify(body)});let result=await response.json();if(!response.ok)throw Error(result.error||'操作失败');return result}
function safely(fn){return async(...args)=>{try{await fn(...args)}catch(error){message(error.message,'需要处理')}}}
function snapshot(){boxHistory.push(JSON.stringify(boxes));if(boxHistory.length>50)boxHistory.shift()}
function edited(){dirty=true;$('dirtyBadge').textContent='有未保存的修改';$('annotationBadge').textContent='草稿';$('annotationBadge').className='badge';$('negativeFrame').checked=false;renderBoxes();draw()}
function selectOptions(element,items,placeholder,previous){element.replaceChildren();if(placeholder){let o=new Option(placeholder,'');element.add(o)}for(let [value,label] of items)element.add(new Option(label,value));if([...element.options].some(o=>o.value===previous))element.value=previous}
async function refresh(){state=await api('/api/lab/state');token=state.token;const count=state.videos.reduce((a,v)=>a+v.reviewed_frames.length,0);$('dataSummary').textContent=`${state.videos.length} 段视频 · ${count} 帧已确认 · ${state.datasets.length} 个数据版本 · ${state.models.length} 个颗粒模型`;
 let previous=$('videoSelect').value;selectOptions($('videoSelect'),state.videos.map(v=>[v.id,v.name]),null,previous);
 let model=$('modelSelect').value||state.active_model?.model_id;selectOptions($('modelSelect'),state.models.map(m=>[m.id,`${m.architecture.replace('.pt','')} · ${m.id}${m.qualification==='exploratory_single_video'?' · 单视频试训':''}`]),state.models.length?null:'尚无训练完成的颗粒模型',model);
 selectOptions($('initialModel'),state.models.map(m=>[m.id,m.id]),'官方预训练权重（首次训练）',$('initialModel').value);
 selectOptions($('datasetSelect'),state.datasets.map(d=>[d.id,`${d.id} · 训练 ${d.counts.train} / 验证 ${d.counts.val}`]),state.datasets.length?null:'先创建数据版本',$('datasetSelect').value);
 $('trainModel').disabled=!state.datasets.length;$('previewDetections').disabled=!state.models.length;$('activateModel').disabled=!state.models.length;modelNote();renderRecords();
 if(state.job.busy&&!pollTimer){jobId=state.job.id;pollTimer=setInterval(pollJob,1000);await pollJob()}
}
function modelNote(){const model=state.models.find(m=>m.id===$('modelSelect').value);$('modelQualification').textContent=model?(model.qualification==='exploratory_single_video'?'这个模型来自单视频试训，尚不能据此判断新实验效果。':'此模型使用按实验隔离的数据验证；仍需检查当前视频中的识别和身份。'):'目前尚无 TEM 训练模型。先在“标注数据”中确认标注，再创建数据版本并训练。'}
function renderRecords(){for(let [id,items] of [['datasetCards',state.datasets],['modelCards',state.models]]){$(id).replaceChildren();if(!items.length){let p=document.createElement('p');p.className='muted';p.textContent=id==='datasetCards'?'创建后会显示数据划分和标注版本。':'训练完成后，会显示模型版本、验证指标和数据来源。';$(id).append(p)}for(let item of items){let div=document.createElement('div');div.className='record';let title=document.createElement('strong');title.textContent=item.id;div.append(title,document.createElement('br'));let text=document.createElement('span');if(id==='datasetCards')text.textContent=`训练 ${item.counts.train} 帧 · 验证 ${item.counts.val} 帧 · 测试 ${item.counts.test} 帧；${item.qualification==='exploratory_single_video'?'单视频试训':'按独立实验划分'}`;else{let metrics=item.validation_metrics||{};text.textContent=`${item.architecture} · ${item.epochs_completed} 轮 · mAP50 ${Number(metrics['metrics/mAP50(B)']??NaN).toFixed(3)} · mAP50–95 ${Number(metrics['metrics/mAP50-95(B)']??NaN).toFixed(3)}；数据：${item.dataset_id}`;}div.append(text);for(let warning of item.warnings||[]){let p=document.createElement('p');p.className='muted';p.textContent=warning;div.append(p)}$(id).append(div)}}}
async function setTab(name){if(dirty)await saveAnnotation(false);tabName=name;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$('viewer').hidden=name==='training';$('annotationPanel').hidden=name!=='annotation';$('trainingPanel').hidden=name!=='training';$('trackingPanel').hidden=name!=='tracking';$('timeTracePanel').hidden=name!=='tracking';$('canvasHelp').textContent=name==='tracking'?'先识别当前帧，再点击橙色候选框选中目标。绿色圆圈表示已选择的颗粒。':'拖动鼠标框住颗粒。点击已有框可移动，拖动角点可调整大小。训练标注需要覆盖整帧所有可辨认颗粒。';draw();if(name==='tracking')await refreshTraceResults()}
async function loadVideo(){if(dirty)await saveAnnotation(false);video=state.videos.find(v=>v.id===$('videoSelect').value);resetTraceResults();if(!video)return;$('videoMeta').textContent=`${video.width} × ${video.height} · ${video.frames} 帧`;$('frameSlider').max=video.frames-1;$('imageCanvas').width=video.width;$('imageCanvas').height=video.height;$('experimentName').value=video.experiment;$('videoSplit').value=video.split;const saved=await api(`/api/lab/selections?video=${video.id}`);selections=saved.model_id===$('modelSelect').value?saved.particles:[];rows=[];detections=[];suggestions=[];$('suggestions').replaceChildren();renderSelections();$('resultLinks').replaceChildren();$('trackingReview').textContent='';await loadFrame(0);if($('modelSelect').value){const result=await api(`/api/lab/result?video=${video.id}&model=${$('modelSelect').value}`);if(result)showTracking(result,false)}await refreshTraceResults()}
async function loadFrame(next){if(loadingFrame)return;loadingFrame=true;try{if(dirty)await saveAnnotation(false);frame=Math.max(0,Math.min(video.frames-1,next));annotation=await api(`/api/lab/annotation?video=${video.id}&frame=${frame}`);boxes=structuredClone(annotation.boxes);boxHistory=[];selectedBox=null;dirty=false;detections=[];previewModel=null;$('dirtyBadge').textContent='';$('negativeFrame').checked=annotation.negative_confirmed;$('frameSlider').value=frame;$('frameLabel').textContent=`帧 ${frame} / ${video.frames-1}`;$('annotationBadge').textContent=annotation.reviewed?'已确认，可用于训练':boxes.length?'草稿，尚不用于训练':'未标注';$('annotationBadge').className='badge'+(annotation.reviewed?' reviewed':'');$('draftNote').hidden=!boxes.some(b=>b.source==='previous_ROI_proposal_not_ground_truth');image=await new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('无法读取视频帧'));im.src=`/api/lab/frame?video=${video.id}&frame=${frame}`});renderBoxes();draw()}finally{loadingFrame=false}}
function renderBoxes(){$('boxesList').replaceChildren();for(let [i,b] of boxes.entries()){let div=document.createElement('div');div.className='item'+(b.id===selectedBox?' selected':'');let span=document.createElement('span');span.textContent=`颗粒 ${i+1} · ${Math.round(b.x2-b.x1)}×${Math.round(b.y2-b.y1)} px`;span.onclick=()=>{selectedBox=b.id;renderBoxes();draw()};let identity=document.createElement('input');identity.type='number';identity.min=1;identity.placeholder='可选 ID';identity.value=b.instance_id??'';identity.setAttribute('aria-label',`颗粒 ${i+1} 身份 ID`);identity.onchange=()=>{snapshot();b.instance_id=identity.value?+identity.value:null;edited()};let remove=document.createElement('button');remove.textContent='删除';remove.onclick=()=>{snapshot();boxes=boxes.filter(x=>x.id!==b.id);edited()};div.append(span,identity,remove);$('boxesList').append(div)}}
function draw(){if(!image.complete||!image.naturalWidth)return;ctx.clearRect(0,0,video.width,video.height);ctx.drawImage(image,0,0);ctx.lineWidth=2;ctx.font='bold 14px sans-serif';if(tabName==='annotation'){boxes.forEach((b,i)=>drawBox(b,b.id===selectedBox?'#3aff93':annotation?.reviewed&&!dirty?'#6affb0':'#ffcf57',i+1,b.id===selectedBox));if(ghost)drawBox(ghost,'#44ffaa','',false)}else if(tabName==='tracking'){for(let [i,d] of detections.entries())drawBox(d,'#ffc45c',`${i+1} · ${d.confidence.toFixed(2)}`,false);for(let id of [...new Set(rows.map(r=>r.track_id))]){let trail=rows.filter(r=>r.track_id===id&&r.frame<=frame&&r.frame>=frame-50).sort((a,b)=>a.frame-b.frame),prev=null;ctx.strokeStyle='#ffed00';for(let r of trail){if(r.observed){if(prev&&prev.frame===r.frame-1&&r.status!=='manual_anchor'){ctx.beginPath();ctx.moveTo(prev.center_x,prev.center_y);ctx.lineTo(r.center_x,r.center_y);ctx.stroke()}prev=r}else prev=null}let now=trail.find(r=>r.frame===frame&&r.observed);if(now)circle(now.center_x,now.center_y,now.radius_px,id)}for(let p of selections.filter(p=>p.frame===frame))circle(p.x,p.y,p.radius,p.id)}}
function drawBox(b,color,label,handles){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.strokeRect(b.x1,b.y1,b.x2-b.x1,b.y2-b.y1);if(label){ctx.fillStyle='#132d24cc';ctx.fillRect(b.x1,Math.max(0,b.y1-19),String(label).length*8+12,19);ctx.fillStyle=color;ctx.fillText(label,b.x1+4,Math.max(14,b.y1-4))}if(handles){ctx.fillStyle=color;for(let [x,y] of [[b.x1,b.y1],[b.x2,b.y1],[b.x2,b.y2],[b.x1,b.y2]])ctx.fillRect(x-4,y-4,8,8)}}
function circle(x,y,r,id){ctx.strokeStyle='#24ff73';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,r,0,2*Math.PI);ctx.stroke();ctx.fillStyle='#ffee00';ctx.beginPath();ctx.arc(x,y,2,0,2*Math.PI);ctx.fill();ctx.fillStyle='#29ff78';ctx.fillText(`#${id}`,Math.min(video.width-30,x+r+2),Math.max(16,y))}
function position(e){const r=$('imageCanvas').getBoundingClientRect();return{x:Math.max(0,Math.min(video.width,(e.clientX-r.left)*video.width/r.width)),y:Math.max(0,Math.min(video.height,(e.clientY-r.top)*video.height/r.height))}}
function hit(point,b){return point.x>=b.x1&&point.x<=b.x2&&point.y>=b.y1&&point.y<=b.y2}
$('imageCanvas').onpointerdown=e=>{if(loadingFrame||!video)return;const p=position(e);if(tabName==='tracking'){selectDetection(p);return}if(tabName!=='annotation')return;$('imageCanvas').setPointerCapture(e.pointerId);let b=boxes.find(b=>b.id===selectedBox),corner=-1;const tolerance=10*video.width/$('imageCanvas').getBoundingClientRect().width;if(b)corner=[[b.x1,b.y1],[b.x2,b.y1],[b.x2,b.y2],[b.x1,b.y2]].findIndex(([x,y])=>Math.hypot(p.x-x,p.y-y)<tolerance);if(corner>=0){snapshot();drag={type:'resize',start:p,box:b,original:{...b},corner};return}b=[...boxes].reverse().find(b=>hit(p,b));if(b){selectedBox=b.id;snapshot();drag={type:'move',start:p,box:b,original:{...b}};renderBoxes();draw()}else{selectedBox=null;drag={type:'draw',start:p};ghost={x1:p.x,y1:p.y,x2:p.x,y2:p.y};draw()}};
$('imageCanvas').onpointermove=e=>{if(!drag)return;let p=position(e),s=drag.start;if(drag.type==='draw')ghost={x1:Math.min(p.x,s.x),y1:Math.min(p.y,s.y),x2:Math.max(p.x,s.x),y2:Math.max(p.y,s.y)};if(drag.type==='move'){let b=drag.box,o=drag.original,dx=Math.max(-o.x1,Math.min(video.width-o.x2,p.x-s.x)),dy=Math.max(-o.y1,Math.min(video.height-o.y2,p.y-s.y));Object.assign(b,{x1:o.x1+dx,x2:o.x2+dx,y1:o.y1+dy,y2:o.y2+dy})}if(drag.type==='resize'){let b=drag.box,o=drag.original;const left=[0,3].includes(drag.corner),top=[0,1].includes(drag.corner);b.x1=left?Math.min(p.x,o.x2-2):o.x1;b.x2=left?o.x2:Math.max(p.x,o.x1+2);b.y1=top?Math.min(p.y,o.y2-2):o.y1;b.y2=top?o.y2:Math.max(p.y,o.y1+2)}draw()};
$('imageCanvas').onpointerup=()=>{if(!drag)return;if(drag.type==='draw'){if(ghost.x2-ghost.x1>=2&&ghost.y2-ghost.y1>=2){snapshot();let b={...ghost,id:crypto.randomUUID(),instance_id:null,source:'manual'};boxes.push(b);selectedBox=b.id;edited()}}else{drag.box.source='manual';edited()}drag=null;ghost=null;draw()};
async function saveAnnotation(reviewed){if(!video)return;const result=await api('/api/lab/annotation',{video_id:video.id,frame,boxes,reviewed,negative_confirmed:$('negativeFrame').checked,revision:annotation.revision});annotation=result;dirty=false;$('dirtyBadge').textContent='';$('annotationBadge').textContent=reviewed?'已确认，可用于训练':'草稿，尚不用于训练';$('annotationBadge').className='badge'+(reviewed?' reviewed':'');await refresh();draw();message(reviewed?'已保存完整标注。它会进入下一次创建的数据版本。':'草稿已保存，尚不会用于训练。')}
function renderSelections(){const chosen=$('selectionMode').value;selectOptions($('selectionMode'),[...new Set(selections.map(p=>p.id))].sort((a,b)=>a-b).map(id=>[String(id),`校正目标 #${id}`]),'新增跟踪目标',chosen);$('selectionMode').options[0].value='new';if(!chosen)$('selectionMode').value='new';$('selectedList').replaceChildren();for(let id of [...new Set(selections.map(p=>p.id))]){let list=selections.filter(p=>p.id===id),div=document.createElement('div');div.className='item';let text=document.createElement('span');text.textContent=`目标 #${id} · ${list.length} 个锚点 · 起始帧 ${Math.min(...list.map(p=>p.frame))}`;let b=document.createElement('button');b.textContent='移除';b.onclick=safely(async()=>{selections=selections.filter(p=>p.id!==id);await saveSelections();renderSelections();draw()});div.append(text,b);$('selectedList').append(div)}}
async function saveSelections(){if(!$('modelSelect').value)return;await api('/api/lab/selections',{video_id:video.id,model_id:$('modelSelect').value,particles:selections})}
function selectDetection(point){const d=detections.filter(d=>hit(point,d)).sort((a,b)=>Math.hypot((a.x1+a.x2)/2-point.x,(a.y1+a.y2)/2-point.y)-Math.hypot((b.x1+b.x2)/2-point.x,(b.y1+b.y2)/2-point.y))[0];if(!d){message('请先识别当前帧，再点击模型给出的候选框。');return}if(previewModel!==$('modelSelect').value){message('模型已更换，请重新识别当前帧。');return}const minimum=$('association').value==='trackpy'?Math.min(state.config.association.track_high_thresh,+$('newTrackScore').value):+$('newTrackScore').value;if(d.confidence<minimum){message(`候选分数 ${d.confidence.toFixed(2)} 低于当前起始门限 ${minimum.toFixed(2)}。请先复核识别，或调整新目标最低检测分。`);return}const mode=$('selectionMode').value,id=mode==='new'||mode===''?Math.max(0,...selections.map(p=>p.id))+1:+mode;const p={id,frame,x:(d.x1+d.x2)/2,y:(d.y1+d.y2)/2,radius:Math.max(4,Math.min(Math.max(d.x2-d.x1,d.y2-d.y1)/2,Math.min(video.width,video.height)/3))};if(selections.some(s=>s.id!==id&&s.frame===frame&&Math.hypot(s.x-p.x,s.y-p.y)<2)){message('这个候选已经被选中。');return}selections=selections.filter(p=>!(p.id===id&&p.frame===frame));selections.push(p);renderSelections();draw();saveSelections().catch(e=>message(e.message));message(`已选择目标 #${id}。运行追踪后生成视频和坐标。`)}
function showTracking(result,refreshTraces=true){rows=result.rows;draw();$('resultLinks').replaceChildren();for(let [label,file] of [['追踪视频','annotated.mp4'],['坐标 CSV','tracks.csv'],['待复核清单','review_required.csv'],['逐粒统计','track_statistics.csv'],['轨迹图','trajectories.png']]){let a=document.createElement('a');a.textContent=label;a.href=result.base+file;a.target='_blank';$('resultLinks').append(a)}$('trackingReview').textContent=`模型 ${result.metrics.model_id}；缺测 ${result.metrics.review_rows} 个目标帧。身份准确性仍需逐帧核查。`;message(`完成：${result.metrics.observed_rows}/${result.metrics.observation_rows} 个目标帧有观测。观测率不是准确率。`,'追踪结果已导出');if(refreshTraces)void refreshTraceResults()}
function traceSource(){return traceResults.find(result=>result.id===$('traceResultSelect').value)}
function traceStatus(text,error=false){$('traceStatus').textContent=text;$('traceStatus').dataset.error=String(error)}
function tracePayload(){return{video_id:video?.id,result_id:$('traceResultSelect').value,track_ids:[...$('traceIds').querySelectorAll('input:checked')].map(input=>Number(input.value)).sort((a,b)=>a-b),frame_start:Number($('traceFrameStart').value),frame_end:Number($('traceFrameEnd').value),circle_interval:Number($('traceCircleInterval').value)}}
function updateTraceControls(){const available=Boolean(traceSource());$('traceResultSelect').disabled=traceLoading||!traceResults.length;$('traceOptions').disabled=traceLoading||!available;$('generateTimeTrace').disabled=traceBusy||traceLoading||!available;$('generateTimeTrace').textContent=traceBusy?'正在生成…':'生成时间痕迹图'}
function invalidateTracePreview(text='设置已更新，点击“生成时间痕迹图”查看效果。'){
 tracePreviewVersion++;$('traceFigure').hidden=true;$('traceImage').removeAttribute('src');$('traceCaption').textContent='';
 for(const id of ['traceOpenImage','traceDownloadImage','traceDownloadMetadata'])$(id).removeAttribute('href');
 traceStatus(text);updateTraceControls();
}
function resetTraceResults(){
 traceFetchVersion++;traceVideoId=null;traceResults=[];traceLoading=false;
 selectOptions($('traceResultSelect'),[],'正在读取追踪结果…');$('traceIds').replaceChildren();
 invalidateTracePreview('正在读取追踪结果…');
}
function selectTraceSource(){
 const source=traceSource();$('traceIds').replaceChildren();
 if(!source){invalidateTracePreview('当前视频没有可用追踪结果。请先识别、选择颗粒并运行追踪。');return}
 for(const id of source.track_ids){const label=document.createElement('label');label.className='trace-target';const input=document.createElement('input');input.type='checkbox';input.value=String(id);input.checked=true;input.onchange=()=>invalidateTracePreview();label.append(input,document.createTextNode(`颗粒 ${id}`));$('traceIds').append(label)}
 for(const id of ['traceFrameStart','traceFrameEnd']){const input=$(id);input.min=source.frame_start;input.max=source.frame_end}
 $('traceFrameStart').value=source.frame_start;$('traceFrameEnd').value=source.frame_end;$('traceCircleInterval').value=5;
 invalidateTracePreview('已选全部颗粒和完整帧范围，点击生成查看圆圈残影。');
}
async function refreshTraceResults(){
 if(!video)return;
 const videoId=video.id,request=++traceFetchVersion;traceLoading=true;updateTraceControls();
 try{
  const result=await api(`/api/lab/trace-results?video=${encodeURIComponent(videoId)}`);
  if(request!==traceFetchVersion||video?.id!==videoId)return;
  const previous=traceVideoId===videoId?traceSource():null;
  traceResults=result.results||[];traceVideoId=videoId;
  selectOptions($('traceResultSelect'),traceResults.map(item=>[item.id,item.label]),traceResults.length?null:'当前视频尚无追踪结果',previous?.id);
  const current=traceSource(),rangeKey=item=>item?JSON.stringify([item.id,item.track_ids,item.frame_start,item.frame_end]):null;
  if(!current||rangeKey(previous)!==rangeKey(current))selectTraceSource();
 }catch(error){
  if(request!==traceFetchVersion||video?.id!==videoId)return;
  traceStatus(`无法读取追踪结果：${error.message}。重新进入“识别与追踪”可重试。`,true);
 }finally{if(request===traceFetchVersion){traceLoading=false;updateTraceControls()}}
}
async function generateTimeTrace(){
 if(traceBusy)return;
 const source=traceSource(),payload=tracePayload();
 if(!source){traceStatus('请先选择一份追踪结果。',true);return}
 if(!payload.track_ids.length){traceStatus('请至少选择一个颗粒。',true);return}
 if(!$('traceFrameStart').value.trim()||!$('traceFrameEnd').value.trim()||![payload.frame_start,payload.frame_end].every(Number.isInteger)||payload.frame_start<source.frame_start||payload.frame_end>source.frame_end||payload.frame_start>payload.frame_end){traceStatus(`请输入 ${source.frame_start}–${source.frame_end} 范围内的整数帧号，起始帧不能晚于结束帧。`,true);return}
 if(!Number.isInteger(payload.circle_interval)||payload.circle_interval<1){traceStatus('圆圈间隔需要是大于 0 的整数帧数。',true);return}
 invalidateTracePreview('正在绘制中心路径与圆圈残影…');traceBusy=true;updateTraceControls();
 const version=tracePreviewVersion,signature=JSON.stringify(payload),sourceLabel=source.label;
 try{
  const result=await api('/api/lab/time-traces',payload);
  if(version!==tracePreviewVersion||signature!==JSON.stringify(tracePayload()))return;
  $('traceImage').src=result.image_url;$('traceImage').alt=`${sourceLabel}，颗粒 ${payload.track_ids.join('、')}，帧 ${payload.frame_start} 至 ${payload.frame_end} 的中心路径与圆圈残影`;
  $('traceOpenImage').href=result.image_url;$('traceDownloadImage').href=result.image_url;$('traceDownloadImage').download=`time_traces_F${payload.frame_start}-F${payload.frame_end}.png`;
  $('traceDownloadMetadata').hidden=!result.metadata_url;if(result.metadata_url){$('traceDownloadMetadata').href=result.metadata_url;$('traceDownloadMetadata').download=`time_traces_F${payload.frame_start}-F${payload.frame_end}.json`}
  $('traceCaption').textContent=`${sourceLabel} · 颗粒 ${payload.track_ids.join('、')} · 帧 ${payload.frame_start}–${payload.frame_end} · 每 ${payload.circle_interval} 帧保留圆圈（每个颗粒的首次和最后有效位置也保留）`;
  $('traceFigure').hidden=false;
  const missing=result.missing_ids||[];
  traceStatus(`已生成：${result.observed_count} 个有效位置，${result.circle_count} 个定位圆圈。${missing.length?`颗粒 ${missing.join('、')} 在所选范围没有有效观测，未绘制。`:''}`);
 }catch(error){if(version===tracePreviewVersion)traceStatus(`生成失败：${error.message}`,true)}
 finally{traceBusy=false;updateTraceControls()}
}
async function startJob(action,payload={}){if(dirty)await saveAnnotation(false);const job=await api('/api/lab/job',{action,...payload});jobId=job.id;$('jobLog').href=job.log;$('jobLog').hidden=false;$('cancelJob').hidden=false;message('任务已启动。训练期间仍可继续标注。','正在处理');if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(pollJob,1000);await pollJob()}
async function pollJob(){try{const job=await api('/api/lab/job');if(job.id!==jobId)return;let p=job.progress||{};$('jobLog').href=job.log||'#';$('jobLog').hidden=!job.log;$('cancelJob').hidden=!job.busy;$('jobProgress').hidden=!job.busy;let total=p.epochs||p.frames,done=p.epoch||p.frame||0;if(total){$('jobProgress').value=100*done/total}else $('jobProgress').removeAttribute('value');if(job.busy){message(p.message||'正在执行任务…',job.action==='train'?'正在训练模型':'正在处理');return}clearInterval(pollTimer);pollTimer=null;$('jobProgress').hidden=true;if(job.status!=='completed'){message(job.error||'任务未完成','任务已停止');return}let result=job.result;await refresh();if(job.action==='dataset'){$('datasetSelect').value=result.id;message(`数据版本已创建：训练 ${result.counts.train} 帧、验证 ${result.counts.val} 帧。${result.warnings.join('； ')}`,'数据已准备')}if(job.action==='train'){$('modelSelect').value=result.id;modelNote();message('训练完成，新模型已保存。可到“识别与追踪”中检查识别结果。','模型已训练')}if(job.action==='preview'){if(result.video_id===video.id&&result.frame===frame){detections=result.detections;previewModel=result.model_id;draw();message(`当前帧识别到 ${detections.length} 个候选，请点击需要追踪的颗粒。`,'识别完成')}else message('识别已完成，但当前帧已改变，请重新识别。')}if(job.action==='suggest'){suggestions=result.frames;$('suggestions').replaceChildren();for(let s of suggestions){let b=document.createElement('button');b.textContent=`帧 ${s.frame}`;b.title=s.reason;b.onclick=safely(()=>loadFrame(s.frame));$('suggestions').append(b)}message(`已推荐 ${suggestions.length} 帧，点击帧号开始标注。`)}if(job.action==='track'){if(result.video_id===video.id&&result.model_id===$('modelSelect').value)showTracking(result);else message('追踪已完成。请切回原视频和模型查看结果。')}if(job.action==='evaluate')message(JSON.stringify(result.metrics),'评估完成')}catch(e){clearInterval(pollTimer);pollTimer=null;message(e.message,'读取任务失败')}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=safely(()=>setTab(b.dataset.tab)));
$('videoSelect').onchange=safely(loadVideo);$('frameSlider').onchange=safely(()=>loadFrame(+$('frameSlider').value));$('previousFrame').onclick=safely(()=>loadFrame(frame-1));$('nextFrame').onclick=safely(()=>loadFrame(frame+1));
$('saveDraft').onclick=safely(()=>saveAnnotation(false));$('confirmAnnotation').onclick=safely(()=>saveAnnotation(true));$('negativeFrame').onchange=()=>{dirty=true;$('dirtyBadge').textContent='有未保存的修改'};
$('undoBox').onclick=()=>{if(boxHistory.length){boxes=JSON.parse(boxHistory.pop());edited()}};$('removeBox').onclick=()=>{if(selectedBox){snapshot();boxes=boxes.filter(b=>b.id!==selectedBox);selectedBox=null;edited()}};
$('copyPrevious').onclick=safely(async()=>{if(!frame)throw Error('当前已经是首帧');const previous=await api(`/api/lab/annotation?video=${video.id}&frame=${frame-1}`);snapshot();boxes=previous.boxes.map(b=>({...b,id:crypto.randomUUID(),source:'copied_previous_frame_needs_review'}));edited();message('已复制上一帧的框，请逐个调整位置和大小，补全后再确认。')});
$('exportAnnotation').onclick=()=>{let link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify({...annotation,boxes,reviewed:dirty?false:annotation.reviewed},null,2)],{type:'application/json'}));link.download=`${video.id}_frame_${frame}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
$('saveVideoGroup').onclick=safely(async()=>{await api('/api/lab/video',{video_id:video.id,experiment:$('experimentName').value,split:$('videoSplit').value});await refresh();message('实验分组已保存；此前固定的数据版本保持原样。')});
$('importVideo').onclick=safely(async()=>{let file=$('videoFile').files[0];if(!file)throw Error('请选择视频文件');if(!$('newExperiment').value.trim())throw Error('请填写独立实验组名称');if(dirty)await saveAnnotation(false);message('正在复制并核对视频…');let v=await api(`/api/lab/import-video?name=${encodeURIComponent(file.name)}&experiment=${encodeURIComponent($('newExperiment').value)}`,file,true);await refresh();$('videoSelect').value=v.id;await loadVideo();message('视频已导入，可以开始标注。')});
$('buildDataset').onclick=safely(()=>startJob('dataset',{split_mode:$('splitMode').value,temporal_gap:+$('temporalGap').value}));
$('trainModel').onclick=safely(()=>startJob('train',{dataset_id:$('datasetSelect').value,epochs:+$('epochs').value,batch:+$('batch').value,imgsz:+$('imageSize').value,initial_model_id:$('initialModel').value||null}));
$('modelSelect').onchange=safely(async()=>{detections=[];rows=[];selections=[];previewModel=null;modelNote();renderSelections();draw();message('模型已更换，请重新识别并选择目标。')});
$('previewDetections').onclick=safely(()=>startJob('preview',{video_id:video.id,frame,model_id:$('modelSelect').value}));
$('activateModel').onclick=safely(async()=>{await api('/api/lab/activate',{model_id:$('modelSelect').value});message('默认颗粒模型已保存，下次打开时继续使用。')});
$('suggestFrames').onclick=safely(()=>startJob('suggest',{video_id:video.id,model_id:$('modelSelect').value||null}));
$('clearSelected').onclick=safely(async()=>{selections=[];await saveSelections();renderSelections();draw();message('已清空跟踪选择。')});
$('usePredictions').onclick=safely(async()=>{if(!detections.length)throw Error('当前没有识别框，请先识别当前帧');snapshot();boxes=detections.map(d=>({...d,id:crypto.randomUUID(),instance_id:null,source:`model_proposal:${previewModel}`}));edited();await saveAnnotation(false);await setTab('annotation');message('识别框已保存为标注草稿。请检查漏检、误检和框的位置，然后确认完整标注。')});
$('runTracking').onclick=safely(()=>{if(!selections.length)throw Error('请先识别并点击选择颗粒');return startJob('track',{video_id:video.id,model_id:$('modelSelect').value,particles:selections,association:$('association').value,new_track_thresh:+$('newTrackScore').value,calibration:{acquisition_fps:$('acquisitionFps').value?+$('acquisitionFps').value:null,nm_per_pixel:$('pixelSize').value?+$('pixelSize').value:null}})});
$('cancelJob').onclick=safely(async()=>{await api('/api/lab/cancel',{});await pollJob()});
$('traceResultSelect').onchange=selectTraceSource;
for(const id of ['traceFrameStart','traceFrameEnd','traceCircleInterval'])$(id).oninput=()=>invalidateTracePreview();
$('traceSelectAll').onclick=()=>{for(const input of $('traceIds').querySelectorAll('input'))input.checked=true;invalidateTracePreview()};
$('traceSelectNone').onclick=()=>{for(const input of $('traceIds').querySelectorAll('input'))input.checked=false;invalidateTracePreview()};
$('generateTimeTrace').onclick=generateTimeTrace;
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
safely(async()=>{await refresh();await loadVideo()})();
